Add the type and new expressions in the Go implementation and fix a major bug in the Python implementation
This changeset adds the `type` keyword & expression, as well as the
`new` keyword and expression, to the go implementation. With the
addition of these expressions, every expression kind within the Python
implementation has now been added the Go implementation.

    $ mf --dump-ast --command 'new type {"foo": function(){}} {"bar": "baz"};'
    {
        "kind": "AstProgram",
        "location": {
            "file": "<command>",
            "line": 1
        },
        "statements": [
            {
                "kind": "AstStatementExpression",
                "location": {
                    "file": "<command>",
                    "line": 1
                },
                "expression": {
                    "kind": "AstExpressionNew",
                    "location": {
                        "file": "<command>",
                        "line": 1
                    },
                    "meta": {
                        "kind": "AstExpressionType",
                        "location": {
                            "file": "<command>",
                            "line": 1
                        },
                        "name": "type",
                        "expression": {
                            "kind": "AstExpressionMap",
                            "location": {
                                "file": "<command>",
                                "line": 1
                            },
                            "elements": [
                                [
                                    {
                                        "kind": "AstExpressionString",
                                        "location": {
                                            "file": "<command>",
                                            "line": 1
                                        },
                                        "data": "foo"
                                    },
                                    {
                                        "kind": "AstExpressionFunction",
                                        "location": {
                                            "file": "<command>",
                                            "line": 1
                                        },
                                        "paramters": [],
                                        "body": {
                                            "kind": "AstBlock",
                                            "location": {
                                                "file": "<command>",
                                                "line": 1
                                            },
                                            "statements": []
                                        },
                                        "name": null
                                    }
                                ]
                            ]
                        }
                    },
                    "expression": {
                        "kind": "AstExpressionMap",
                        "location": {
                            "file": "<command>",
                            "line": 1
                        },
                        "elements": [
                            [
                                {
                                    "kind": "AstExpressionString",
                                    "location": {
                                        "file": "<command>",
                                        "line": 1
                                    },
                                    "data": "bar"
                                },
                                {
                                    "kind": "AstExpressionString",
                                    "location": {
                                        "file": "<command>",
                                        "line": 1
                                    },
                                    "data": "baz"
                                }
                            ]
                        ]
                    }
                }
            }
        ]
    }

When implementing this changeset, a major bug was discovered within the
AstExpressionNew.eval method from the Python implementation. Previously,
the eval method was erroneously defined as follows:

    def eval(self, env: Environment) -> Union[Value, Error]:
        meta = self.meta.eval(env)
        if isinstance(meta, Error):
            return meta
        expression = self.expression.eval(env)
        if isinstance(expression, Error):
            return expression
        if isinstance(meta, Map):
            if not meta.name:
                return Error(
                    self.meta.location,
                    f"expected map-like value created with the {quote(TokenKind.TYPE)} expression, received regular map value {meta}",
                )
            expression.meta = copy(meta) # BUG HERE: THE EXPRESSION IS NEVER COPIED BEFORE META IS SET!!!
            return expression
        return Error(
            self.meta.location,
            f"expected map-like value, received {typename(meta)}",
        )

In this implementation, the line:

    expression.meta = copy(meta)

used the expression result from the line:

    expression = self.expression.eval(env)

without ever making a copy of that expression. Evaluation of an
expression may result in an arbitrary non-copied value being produced.
For example, an identifier expression will produce the same object that
is stored in an environment verbatim. So in the code above, evaluating a
new expression and setting its metamap had the potential to alter the
metamap of an arbitrary other object, creating spooky action at a
distance.

    $ ./mf.py
    >>> let T = type Map{"foo": "bar"};
    >>> let x = new T null;
    >>> dumpln(typeof(x));
    {"foo": "bar"}
    >>> dumpln(typeof(null));
    {"foo": "bar"}

This changeset updates AstExpressionNew.eval to correctly copy the
produced expression *before* updating that expression's metamap:

    def eval(self, env: Environment) -> Union[Value, Error]:
        meta = self.meta.eval(env)
        if isinstance(meta, Error):
            return meta
        value = self.expression.eval(env)
        if isinstance(value, Error):
            return value
        if not isinstance(meta, Map):
            return Error(
                self.meta.location,
                f"expected map-like value, received {typename(meta)}",
            )
        if not isinstance(value, Map):
            return Error(
                self.meta.location,
                f"expected map-like value, received {typename(value)}",
            )
        if not meta.name:
            return Error(
                self.meta.location,
                f"expected map-like value created with the {quote(TokenKind.TYPE)} expression, received regular map value {meta}",
            )
        value = copy(value)
        value.cow()
        value.meta = copy(meta)
        return value

However, this revealed a language design flaw. We specifically make some
types immutable in order to avoid constantly heap allocating copies of
those objects during copy operations. For these objects, performing a
copy operation is effectively a no-op, meaning that the same object is
returned. Since a copy does not guarantee a unique object allocation, we
could still run into the problem where setting the metamap of a copy
creates spooky action at a distance.

To fix this, the language has been updated to only allow maps to be
created with the `new` keyword. Since maps are container types with
copy-on-write data, we know that performing a copy operation on a map
creates a new object every time. Since the common case for the `new`
expression to to create a map with specific behavior defined by a type,
it makes sense to just have it be a language rule that one *must* use a
map as the target of the `new` expression. Theoretically, we could do
something similar for vector and set types as well, but I would rather
keep the language simple and just cater to the common case for now.
After implementing these fixes, attempting to create a non-map object
with a `new` expression results in an error:

    $ ./mf.py
    >>> let T = type Map{"foo": "bar"};
    >>> let x = new T null;
    error: expected map-like value, received null