Fix incorrect error message in string::slice and vector::slice
This changeset fixes incorrect error messages in the Python
implementation's string::slice() and vector::slice() where "begin index"
was used instead of "end index":

    $ python3 mf.py -c '["foo"].slice(0, 3);'
    error: attempted vector::slice with invalid begin index 3 (vector has a count of 1)
    ...within vector::slice@builtin called from <command>, line 1

With this changeset, the error message now correctly says that the end
index was invalid:

    $ python3 mf.py -c '["foo"].slice(0, 3);'
    error: attempted vector::slice with invalid end index 3 (vector has a count of 1)
    ...within vector::slice@builtin called from <command>, line 1