Fix mismatched error messages for fs::write and fs::append
This changeset fixes some currently unaligned error messages in the
Python and Go implementations. Prior to this changeset, the Python and
Go implementations of fs::write() and fs::append() diverged in the
non-errno portion of their error messages:

    $ python3 mf.py -c 'fs::write("/dev/urandom", "nope");'
    error: failed write to file "/dev/urandom" ([Errno 1] Operation not permitted)
    ...within fs::write@builtin called from <command>, line 1

    $ mf -c 'fs::write("/dev/urandom", "nope");'
    error: failed to write file "/dev/urandom" (write /dev/urandom: operation not permitted)
    ...within fs::write@builtin called from <command>, line 1

With this changeset, the Go implementation is updated to align with the
Python implementation's wording:

    $ mf -c 'fs::write("/dev/urandom", "nope");'
    error: failed write to file "/dev/urandom" (write /dev/urandom: operation not permitted)
    ...within fs::write@builtin called from <command>, line 1