Make the Wasm fs::append create a file if it does not exist
This changeset updates the behavior of the WebAssembly fs::append()
function to create a new file when appending to a file that does not
already exist. Prior to this changeset, attempting to call fs::append()
on a file not present in the virtual filesystem would produce an error:

    try { dumpln(fs::read("x.txt")); } catch err { eprintln(err); }
    fs::append("x.txt", "SOME TEXT");
    try { dumpln(fs::read("x.txt")); } catch err { eprintln(err); }
    --------
    failed to read file "x.txt" (file not found)
    error: failed to read file "x.txt" (file not found)
    ...within fs::append@builtin called from <program>, line 2

With this changeset in place, attempting to call fs::append() on a file
not present in the virtual filesystem will now create a new file with
the desired contents:

    try { dumpln(fs::read("x.txt")); } catch err { eprintln(err); }
    fs::append("x.txt", "SOME TEXT");
    try { dumpln(fs::read("x.txt")); } catch err { eprintln(err); }
    --------
    failed to read file "x.txt" (file not found)
    "SOME TEXT"

With this and other recent work bringing the WebAssembly build up to
reasonable parity with the native implementation, this changeset will
also mark WebAssembly support as non-experimental.