Validate that method calls js::value::call are invoked through a valid JavaScript method
Previously, method calls made though js::value::call could cause a
runtime panic, as there were no checks in place to ensure that the call
was being invoked on a JavaScript object with the provided named method.
This changeset adds such checks so that the Mellifera snippet:

    js::global().set("foo", js::from_mellifera("bar"));
    js::global().call("foo", [js::from_mellifera(123)]);

now produces there error:

    error: external value external(<object>) is does not have method foo (found external(bar))
    ...within js::value::call@builtin called from <program>, line 2