Add --dump-tokens flag
This changeset introduces a new flag to mf.py, --dump-tokens, which will
print a comb-encoded representation of tokens lexed from a command or
source file to stdout.

    $ mf --dump-tokens -c 'foo 123.456 "bar" r`^.*$`'
    [
        {
            "kind": "identifier",
            "literal": "foo",
            "location": {
                "file": "<command>",
                "line": 1
            }
        },
        {
            "kind": "number",
            "literal": "123.456",
            "location": {
                "file": "<command>",
                "line": 1
            }
        },
        {
            "kind": "string",
            "literal": "\"bar\"",
            "location": {
                "file": "<command>",
                "line": 1
            }
        },
        {
            "kind": "regexp",
            "literal": "r`^.*$`",
            "location": {
                "file": "<command>",
                "line": 1
            }
        }
    ]

    $ mf --dump-tokens examples/hello-world.mf
    [
        {
            "kind": "identifier",
            "literal": "println",
            "location": {
                "file": "examples/hello-world.mf",
                "line": 1
            }
        },
        {
            "kind": "(",
            "literal": "(",
            "location": {
                "file": "examples/hello-world.mf",
                "line": 1
            }
        },
        {
            "kind": "string",
            "literal": "\"Hello, world!\"",
            "location": {
                "file": "examples/hello-world.mf",
                "line": 1
            }
        },
        {
            "kind": ")",
            "literal": ")",
            "location": {
                "file": "examples/hello-world.mf",
                "line": 1
            }
        },
        {
            "kind": ";",
            "literal": ";",
            "location": {
                "file": "examples/hello-world.mf",
                "line": 1
            }
        }
    ]

    $ mf --dump-tokens
    error: requested token dump without a command or file path

Additionally, this changeset replaces the `number` and `string` fields
of the Token class with a single `value` field containing the Mellifera
value of that token's number, string, or regular expression. Originally,
this work was done as part of this changeset in order to facilitate
adding a value field to the token dump output, but given that the comb
representation of a regular expression is not expressible, this change
ended up being architectural only.

This changeset also fixes some minor formatting bugs where f-string
placeholder syntax was used for errors without actually prefixing the
strings with the `f` character.