Add hive::decode, hive::encode, and hive::encode_ex
This changeset introduces HIVE (Hive & hive are also accepted written
forms of HIVE), a JSON-like data format specific to Mellifera. HIVE data
may contain any of the following value types: null, boolean, number (NaN
and Inf not permitted), string, vector, map, and set. HIVE is intended
to be the standard data-interchange format for Mellifera programs,
services, and libraries where a text representation of basic Mellifera
values is required.

    $ mf
    >>> println(hive::encode({"foo": [123, 456], "bar": {.key = "value"}, "baz": {[], Map{}, Set{}}}));
    {"foo": [123, 456], "bar": {"key": "value"}, "baz": {[], Map{}, Set{}}}
    >>> println(hive::encode_ex({"foo": [123, 456], "bar": {.key = "value"}, "baz": {[], Map{}, Set{}}}, {.indent: 4}));
    {
        "foo": [
            123,
            456
        ],
        "bar": {
            "key": "value"
        },
        "baz": {
            [],
            Map{},
            Set{}
        }
    }
    >>> hive::encode(123.&);
    error: cannot HIVE-encode value reference@0x10112cef0 of type reference
    >>> hive::decode(`{"foo": [123, 456], "bar": {.key = "value"}, "baz": {[], Map{}, Set{}}}`);
    {"foo": [123, 456], "bar": {"key": "value"}, "baz": {[], Map{}, Set{}}}

HIVE values are encoded using the new `Value.hive_encode` method
implemented for each value type. HIVE strings are parsed using the
existing Mellifera parser (restricted to literal values), so HIVE syntax
is a subset of the Mellifera language grammar.