Add number::format
This changeset adds number::format() to the standard library, allowing
numbers to be transformed into a formatted string using a printf-like
format specifier.

    $ mf -c 'dumpln((-123.456).format("10f"));'
    "  -123.456"

    $ mf -c 'dumpln((3735928559).format("+#016x"));'
    "+0x00000deadbeef"

The grammar for this format string matches the following regular
expression:

    \+?#?0?\d+?[fdbxX]

The components of the format string are as follows:

    sign (+): Always show sign.
    altf (#): Alternate form => 0b for binary, 0x for hex with base x, 0X
              for hex with base X.
    zero (0): Pad with zeros up to the provided width.
    wstr (width): Minimum total width of the output string.
    base (fdbxX): Digit base => b for binary, x for hex (lower), X for
                  hex (upper), d for decimal integer, f for decimal
                  float.

Attempting to format a non-integer number with any one of the d, b, x,
or X specifiers will produce an error:

    $ mf -c '(123.456).format("x");'
    error: cannot convert 123.456 into an integer without truncation
    ...within number::format@builtin called from <command>, line 1

Attempting to provide an invalid format string will also produce an
error:

    $ mf -c '(123.456).format("oops");'
    error: expected format string matching \+?#?0?\d+?[fdbxX], received "oops"
    ...within number::format@builtin called from <command>, line 1

This changeset does not fully implement the relevant subset of C's
printf specifier grammar: the "-" flag indicating left alignment, and
the precision specifier ".3f", were left out of this initial changeset
to reduce code complexity.

This changeset additionally adds Context.NewRegexpOrPanic() to the Go
implementation. Originally, the changeset used a Mellifera regular
expression value as part of an error message. While working on that
error message, I realized we did not have an equivalent
Context.NewTYPEOrPanic() function for regular expressions, so that
function was added alongside these changes.