Add the freeze keyword and expression
This changeset introduces the freeze keyword and associated expression:

        freeze <expression>

The freeze keyword acts as a unary prefix operator, copying the target
operand and transforming that copy into an immutable value. For values
which are already immutable, the freeze operator is effectively a no-op.
For mutable collection values (vectors, maps, and sets), the freeze
operator makes it so updates to the frozen values using access operators
such as x[field], as well as updates through built-in functions such as
vector::push or map::insert, will produce an error indicating that there
was an attempted modification of an immutable value. Freezing a value
provides deep immutability, recursively freezing elements so that no
modification can be made to any portion of a container's sub-tree.

This changeset also inadvertently fixes a bug that has existed in the
Mellifera interpreter since the type keyword was added for creating
immutable metamaps. The previous way that immutability was defined for
metamaps accidentally allowed for mutability of values within the
sub-tree of the (supposedly) frozen type:

    $ cat test.mf
    let T = type {"foo": {"bar": "baz"}};
    dumpln(T);
    T["foo"]["bar"] = 123;
    dumpln(T);

    $ mf test.mf
    {"foo": {"bar": "baz"}}
    {"foo": {"bar": 123}}

With this changeset, attempting to modify the sub-tree of a frozen type
produces the same flavor of error as when attempting to modify the
sub-tree of any other frozen value:

    $ cat test.mf
    let T = type {"foo": {"bar": "baz"}};
    dumpln(T);
    try { T["foo"]["bar"] = 123; } catch err { println($"error: {err}"); }

    let X = freeze {"foo": {"bar": "baz"}};
    dumpln(X);
    try { X["foo"]["bar"] = 123; } catch err { println($"error: {err}"); }

    $ mf test.mf
    {"foo": {"bar": "baz"}}
    error: attempted to modify immutable map {"bar": "baz"}
    {"foo": {"bar": "baz"}}
    error: attempted to modify immutable map {"bar": "baz"}