Produce an error when exit is called from the Wasm build
This changeset updates the Wasm build of the interpreter to produce an
error when the exit() function is invoked. By default the exit()
function mapped to Go's os.Exit() will halt the running Wasm program,
making subsequent mellifera.eval() operations in JavaScript bubble up
the error:

    Uncaught Error: Go program has already exited

This changeset updates the exit() implementation in the Wasm build to
instead return an error indicating that the function is unsupported:

    error: unsupported function
    ...within exit@builtin called from <program>, line 1