Add import to the Wasm build
This changeset introduces the import() function into the Wasm build,
utilizing the virtual file system that was added in a recent commit. The
import() function mostly follows the behavior of the default built-in
import(), but does *not* attempt to use MELLIFERA_SEARCH_PATH for
lookup. The idea here is that a user will set up the files they want in
their virtual file system when calling into mellifera.eval() and then
specifically look for those files when performing an import. The Wasm
import() function *does* respect files ending with a trailing slash, so
import("somelib/") will still look for the module "somelib/lib.mf" when
performing an import.

This changeset additionally fixes a bug that was in the original
built-in import() function, where importing based on an absolute path
would fail even if the file at that absolute path existed:

    $ mf -c 'dumpln(import("/Users/ashn/sources/mellifera/lib/zen/lib.mf"));'
    error: module "/Users/ashn/sources/mellifera/lib/zen/lib.mf" not found

With this changeset, absolute imports now work as one would expect in
the native Mellifera build:

    $ mf -c 'dumpln(import("/Users/ashn/sources/mellifera/lib/zen/lib.mf"));'
    "this too shall pass"